# Generated by Django 4.0.6 on 2022-07-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='category',
        ),
        migrations.AddField(
            model_name='feeds',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
