# Generated by Django 4.0.6 on 2022-07-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_merchandise_category_feeds_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='farmer_post', to='core.comment'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/merchandise'),
        ),
    ]
