# Generated by Django 4.0.6 on 2022-07-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_feeds_comments_alter_merchandise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='farmer_post', to='core.comment'),
        ),
    ]
